<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
   
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<button>Hiii</button>


<script>Swal.fire(
		  'Good job!',
		  'You clicked the button!',
		  'success'
		)</script>
		
		<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</body>


</html>